#pragma once
//#define GSL_THROW_ON_CONTRACT_VIOLATION
#define GSL_UNENFORCED_ON_CONTRACT_VIOLATION
#include "../numbertest/Number.h"
#include "../Union/Union.h"
#include "../tokentest/Token.h"
#include "../Map/Map.h"
#include "../Set/Set.h"
#include "../Seq/Seq.h"
